// This file is auto-generated by Modern.js. Do not edit manually.

import type { router as router0 } from './index/router.gen';

declare module '@modern-js/plugin-tanstack/runtime' {
  interface Register {
    router: typeof router0;
  }
}

declare module '@modern-js/plugin-i18n/runtime' {
  interface UltramodernCanonicalRoutes {
    '/': Record<string, never>;
    '/course-creation/$courseId/$step': { "courseId": string; "step": string };
    '/dashboard': Record<string, never>;
    '/privacy': Record<string, never>;
    '/sign-in': Record<string, never>;
    '/sign-up': Record<string, never>;
    '/terms': Record<string, never>;
  }
}
