// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  createRouteStaticData,
  type ModernRouterContext,
  modernLoaderToTanstack,
  modernTanstackRouterFastDefaults,
} from '@modern-js/plugin-tanstack/runtime';

import component_0 from "../../routes/[lang]/page";
import component_1 from "../../routes/[lang]/course-creation/[courseId]/[step]/page";
import component_2 from "../../routes/[lang]/dashboard/page";
import component_3 from "../../routes/[lang]/privacy/page";
import component_4 from "../../routes/[lang]/sign-in/page";
import component_5 from "../../routes/[lang]/sign-up/page";
import component_6 from "../../routes/[lang]/terms/page";
import component_7 from "../../routes/layout";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_7,
  staticData: createRouteStaticData({
    modernRouteId: "layout",
  }),
});

const route__lang__page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_0,
  path: "$lang",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/page",
  }),
});

const route__lang__courseCreation__courseId___step__page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_1,
  path: "$lang/course-creation/$courseId/$step",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/course-creation/(courseId)/(step)/page",
  }),
});

const route__lang__courseCreation__courseId___step__page__localised_lang_tvorbaKurzu_courseId_step = createRoute({
  getParentRoute: () => rootRoute,
  component: component_1,
  path: "$lang/tvorba-kurzu/$courseId/$step",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/course-creation/(courseId)/(step)/page__localised_lang_tvorba-kurzu_courseId_step",
  }),
});

const route__lang__dashboard_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_2,
  path: "$lang/dashboard",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/dashboard/page",
  }),
});

const route__lang__dashboard_page__localised_lang_nastenka = createRoute({
  getParentRoute: () => rootRoute,
  component: component_2,
  path: "$lang/nastenka",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/dashboard/page__localised_lang_nastenka",
  }),
});

const route__lang__privacy_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_3,
  path: "$lang/privacy",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/privacy/page",
  }),
});

const route__lang__privacy_page__localised_lang_ochranaOsobnichUdaju = createRoute({
  getParentRoute: () => rootRoute,
  component: component_3,
  path: "$lang/ochrana-osobnich-udaju",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/privacy/page__localised_lang_ochrana-osobnich-udaju",
  }),
});

const route__lang__signIn_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_4,
  path: "$lang/sign-in",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/sign-in/page",
  }),
});

const route__lang__signIn_page__localised_lang_prihlaseni = createRoute({
  getParentRoute: () => rootRoute,
  component: component_4,
  path: "$lang/prihlaseni",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/sign-in/page__localised_lang_prihlaseni",
  }),
});

const route__lang__signUp_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_5,
  path: "$lang/sign-up",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/sign-up/page",
  }),
});

const route__lang__signUp_page__localised_lang_registrace = createRoute({
  getParentRoute: () => rootRoute,
  component: component_5,
  path: "$lang/registrace",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/sign-up/page__localised_lang_registrace",
  }),
});

const route__lang__terms_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_6,
  path: "$lang/terms",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/terms/page",
  }),
});

const route__lang__terms_page__localised_lang_obchodniPodminky = createRoute({
  getParentRoute: () => rootRoute,
  component: component_6,
  path: "$lang/obchodni-podminky",
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/terms/page__localised_lang_obchodni-podminky",
  }),
});

export const routeTree = rootRoute.addChildren([route__lang__page, route__lang__courseCreation__courseId___step__page, route__lang__courseCreation__courseId___step__page__localised_lang_tvorbaKurzu_courseId_step, route__lang__dashboard_page, route__lang__dashboard_page__localised_lang_nastenka, route__lang__privacy_page, route__lang__privacy_page__localised_lang_ochranaOsobnichUdaju, route__lang__signIn_page, route__lang__signIn_page__localised_lang_prihlaseni, route__lang__signUp_page, route__lang__signUp_page__localised_lang_registrace, route__lang__terms_page, route__lang__terms_page__localised_lang_obchodniPodminky]);

export const router = createRouter({
  ...modernTanstackRouterFastDefaults,
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {} as ModernRouterContext,
});
