/* eslint-disable */
// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  notFound,
  redirect,
} from '@modern-js/plugin-tanstack/runtime';

type ModernRouterContext = {
  request?: Request;
  requestContext?: unknown;
};

function isResponse(value: unknown): value is Response {
  return (
    value != null &&
    typeof value === 'object' &&
    typeof (value as any).status === 'number' &&
    typeof (value as any).headers === 'object'
  );
}

const redirectStatusCodes = new Set([301, 302, 303, 307, 308]);
function isRedirectResponse(res: Response) {
  return redirectStatusCodes.has(res.status);
}

function throwTanstackRedirect(location: string) {
  const target = location.length > 0 ? location : '/';
  try {
    void new URL(target);
    throw redirect({ href: target });
  } catch {
    throw redirect({ to: target });
  }
}

function mapParamsForModernLoader(params: Record<string, string>, hasSplat: boolean) {
  if (!hasSplat) {
    return params;
  }

  const { _splat, ...rest } = params as any;
  if (typeof _splat !== 'undefined') {
    return { ...rest, '*': _splat };
  }
  return rest;
}

function createRouteStaticData(opts: {
  modernRouteId?: string;
  modernRouteAction?: unknown;
  modernRouteLoader?: unknown;
}) {
  const staticData: {
    modernRouteId?: string;
    modernRouteAction?: unknown;
    modernRouteLoader?: unknown;
  } = {};

  if (typeof opts.modernRouteId === 'string' && opts.modernRouteId.length > 0) {
    staticData.modernRouteId = opts.modernRouteId;
  }

  if (typeof opts.modernRouteLoader !== 'undefined') {
    staticData.modernRouteLoader = opts.modernRouteLoader;
  }

  if (typeof opts.modernRouteAction !== 'undefined') {
    staticData.modernRouteAction = opts.modernRouteAction;
  }

  return staticData;
}

function getLoaderSignal(ctx: any): AbortSignal {
  const abortSignal = ctx?.abortController?.signal;
  if (abortSignal instanceof AbortSignal) {
    return abortSignal;
  }
  if (ctx?.signal instanceof AbortSignal) {
    return ctx.signal;
  }
  return new AbortController().signal;
}

function getLoaderHref(ctx: any): string {
  if (typeof ctx?.location === 'string') {
    return ctx.location;
  }

  const publicHref = ctx?.location?.publicHref;
  if (typeof publicHref === 'string') {
    return publicHref;
  }

  const href = ctx?.location?.href;
  if (typeof href === 'string') {
    return href;
  }

  const urlHref = ctx?.location?.url?.href;
  return typeof urlHref === 'string' ? urlHref : '';
}

function getLoaderParams(ctx: any): Record<string, string> {
  return typeof ctx?.params === 'object' && ctx.params !== null ? ctx.params : {};
}

function createLoaderRequest(href: string, signal: AbortSignal): Request {
  try {
    return new Request(href, { signal });
  } catch {
    const origin =
      typeof globalThis.location?.origin === 'string' ? globalThis.location.origin : 'http://localhost';
    return new Request(new URL(href || '/', origin), { signal });
  }
}

function handleModernLoaderResult<LoaderResult>(result: LoaderResult): LoaderResult {
  if (isResponse(result)) {
    if (isRedirectResponse(result)) {
      const location = result.headers.get('Location') ?? '/';
      throwTanstackRedirect(location);
    }
    if (result.status === 404) {
      throw notFound();
    }
  }

  return result;
}

function handleModernLoaderError(err: unknown): never {
  if (isResponse(err)) {
    if (isRedirectResponse(err)) {
      const location = err.headers.get('Location') ?? '/';
      throwTanstackRedirect(location);
    }
    if (err.status === 404) {
      throw notFound();
    }
  }

  throw err;
}

function modernLoaderToTanstack<TLoader extends (args: any) => any>(
  opts: { hasSplat: boolean },
  modernLoader: TLoader,
) {
  type LoaderResult = Awaited<ReturnType<TLoader>>;

  return (ctx: any): Promise<LoaderResult> => {
    try {
      const signal = getLoaderSignal(ctx);
      const baseRequest: Request | undefined =
        ctx?.context?.request instanceof Request ? ctx.context.request : undefined;

      const href = getLoaderHref(ctx);

      const request = baseRequest !== undefined
        ? new Request(baseRequest, { signal })
        : createLoaderRequest(href, signal);

      const params = mapParamsForModernLoader(getLoaderParams(ctx), opts.hasSplat);

      return Promise.resolve(
        (modernLoader as any)({
          request,
          params,
          context: ctx?.context?.requestContext,
        }),
      )
        .then((result: LoaderResult) => handleModernLoaderResult(result))
        .catch(handleModernLoaderError);
    } catch (err) {
      handleModernLoaderError(err);
    }
  };
}

import component_0 from "../../routes/layout";
import { loader as loader_0 } from "../../routes/[lang]/page.data";
import { loader as loader_1 } from "../../routes/[lang]/course-creation/[courseId]/[step]/page.data";
import { loader as loader_2 } from "../../routes/[lang]/course-creation/[courseId]/[step]/page.data";
import { loader as loader_3 } from "../../routes/[lang]/dashboard/page.data";
import { loader as loader_4 } from "../../routes/[lang]/dashboard/page.data";
import component_1 from "../../routes/[lang]/page";
import component_2 from "../../routes/[lang]/course-creation/[courseId]/[step]/page";
import component_3 from "../../routes/[lang]/dashboard/page";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_0,
  staticData: createRouteStaticData({
    modernRouteId: "layout",
  }),
});

const route__lang__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang",
  component: component_1,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/page",
    modernRouteLoader: loader_0,
  }),
});

const route__lang__courseCreation__courseId___step__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/course-creation/$courseId/$step",
  component: component_2,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_1),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/course-creation/(courseId)/(step)/page",
    modernRouteLoader: loader_1,
  }),
});

const route__lang__courseCreation__courseId___step__page__localised_lang_tvorbaKurzu_courseId_step = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/tvorba-kurzu/$courseId/$step",
  component: component_2,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_2),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/course-creation/(courseId)/(step)/page__localised_lang_tvorba-kurzu_courseId_step",
    modernRouteLoader: loader_2,
  }),
});

const route__lang__dashboard_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/dashboard",
  component: component_3,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_3),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/dashboard/page",
    modernRouteLoader: loader_3,
  }),
});

const route__lang__dashboard_page__localised_lang_nastenka = createRoute({
  getParentRoute: () => rootRoute,
  path: "$lang/nastenka",
  component: component_3,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_4),
  staticData: createRouteStaticData({
    modernRouteId: "(lang)/dashboard/page__localised_lang_nastenka",
    modernRouteLoader: loader_4,
  }),
});

export const routeTree = rootRoute.addChildren([route__lang__page, route__lang__courseCreation__courseId___step__page, route__lang__courseCreation__courseId___step__page__localised_lang_tvorbaKurzu_courseId_step, route__lang__dashboard_page, route__lang__dashboard_page__localised_lang_nastenka]);

export const router = createRouter({
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {} as ModernRouterContext,
});
