import { workflowSteps } from './workflow';
import type { DraftStep } from './workflow';

export type CourseRouteLanguage = 'en' | 'cs';
export type AuthMode = 'signIn' | 'signUp';
export type LegalDocument = 'privacy' | 'terms';

const authSlugByLanguage = {
  cs: { signIn: 'prihlaseni', signUp: 'registrace' },
  en: { signIn: 'sign-in', signUp: 'sign-up' },
} as const satisfies Record<CourseRouteLanguage, Record<AuthMode, string>>;

const courseBaseSlugByLanguage = {
  cs: 'tvorba-kurzu',
  en: 'course-creation',
} as const satisfies Record<CourseRouteLanguage, string>;

/*
 * The privacy notice and the terms are public reading pages, so each language
 * gets a slug a Czech or English reader would actually type. The English slug
 * is the real file under `src/routes/[lang]/<slug>/` and the Czech spelling is
 * generated by `localisedUrls` in `modern.config.ts`, exactly like the app
 * routes. The pairing below is what the language switcher and the
 * `<link rel="canonical">` tag follow.
 */
const legalSlugByLanguage = {
  cs: { privacy: 'ochrana-osobnich-udaju', terms: 'obchodni-podminky' },
  en: { privacy: 'privacy', terms: 'terms' },
} as const satisfies Record<CourseRouteLanguage, Record<LegalDocument, string>>;

const legalDocuments = ['privacy', 'terms'] as const satisfies readonly LegalDocument[];

const dashboardSlugByLanguage = {
  cs: 'nastenka',
  en: 'dashboard',
} as const satisfies Record<CourseRouteLanguage, string>;

const stepSlugByLanguage = {
  cs: {
    activityPlan: 'plan-aktivit',
    courseContent: 'obsah-kurzu',
    mode: 'rezim',
    objectives: 'cile',
    preparation: 'priprava',
    preview: 'nahled',
    sources: 'zdroje',
  },
  en: {
    activityPlan: 'activity-plan',
    courseContent: 'course-content',
    mode: 'mode',
    objectives: 'objectives',
    preparation: 'preparation',
    preview: 'preview',
    sources: 'sources',
  },
} as const satisfies Record<CourseRouteLanguage, Record<DraftStep, string>>;

const routeSteps = [...workflowSteps, 'preview'] as const satisfies readonly DraftStep[];

export interface CourseRouteMatch {
  draftId: string;
  language: CourseRouteLanguage;
  step: DraftStep;
}

export interface AuthRouteMatch {
  language: CourseRouteLanguage;
  mode: AuthMode;
}

export interface LegalRouteMatch {
  document: LegalDocument;
  language: CourseRouteLanguage;
}

export const isCourseRouteLanguage = (value: string): value is CourseRouteLanguage =>
  value === 'cs' || value === 'en';

export const courseRoutePath = (language: CourseRouteLanguage, draftId: string, step: DraftStep) =>
  `/${language}/${courseBaseSlugByLanguage[language]}/${encodeURIComponent(draftId)}/${
    stepSlugByLanguage[language][step]
  }`;

export const courseRoutePattern = (language: CourseRouteLanguage) =>
  language === 'cs'
    ? '/$lang/tvorba-kurzu/$courseId/$step'
    : '/$lang/course-creation/$courseId/$step';

export const dashboardRoutePath = (language: CourseRouteLanguage) =>
  `/${language}/${dashboardSlugByLanguage[language]}`;

export const dashboardRoutePattern = (language: CourseRouteLanguage) =>
  language === 'cs' ? '/$lang/nastenka' : '/$lang/dashboard';

export const authRoutePath = (language: CourseRouteLanguage, mode: AuthMode) =>
  `/${language}/${authSlugByLanguage[language][mode]}`;

export const authRoutePattern = (language: CourseRouteLanguage, mode: AuthMode) => {
  if (language === 'cs') {
    return mode === 'signIn' ? '/$lang/prihlaseni' : '/$lang/registrace';
  }
  return mode === 'signIn' ? '/$lang/sign-in' : '/$lang/sign-up';
};

export const legalRoutePath = (language: CourseRouteLanguage, document: LegalDocument) =>
  `/${language}/${legalSlugByLanguage[language][document]}`;

export const legalRoutePattern = (language: CourseRouteLanguage, document: LegalDocument) => {
  if (language === 'cs') {
    return document === 'privacy' ? '/$lang/ochrana-osobnich-udaju' : '/$lang/obchodni-podminky';
  }
  return document === 'privacy' ? '/$lang/privacy' : '/$lang/terms';
};

export const courseRouteStepSlug = (language: CourseRouteLanguage, step: DraftStep) =>
  stepSlugByLanguage[language][step];

export const courseRoutesMatch = (
  first: CourseRouteMatch | null,
  second: CourseRouteMatch | null,
) =>
  first?.draftId === second?.draftId &&
  first?.language === second?.language &&
  first?.step === second?.step;

export const parseCourseRoutePath = (pathname: string): CourseRouteMatch | null => {
  const routeSegments = pathname.split('/').filter(Boolean);
  if (routeSegments.length !== 4) {
    return null;
  }
  const [languageSegment, baseSegment, draftIdSegment, stepSegment] = routeSegments;
  const candidateLanguage = languageSegment ?? '';
  if (!isCourseRouteLanguage(candidateLanguage)) {
    return null;
  }
  const language = candidateLanguage;
  if (
    baseSegment !== courseBaseSlugByLanguage[language] ||
    typeof draftIdSegment !== 'string' ||
    draftIdSegment.length === 0 ||
    typeof stepSegment !== 'string' ||
    stepSegment.length === 0
  ) {
    return null;
  }
  const step = routeSteps.find(
    (draftStep) => stepSlugByLanguage[language][draftStep] === stepSegment,
  );
  if (step === undefined) {
    return null;
  }
  let draftId: string;
  try {
    draftId = decodeURIComponent(draftIdSegment);
  } catch {
    return null;
  }
  return {
    draftId,
    language,
    step,
  };
};

export const parseAuthRoutePath = (pathname: string): AuthRouteMatch | null => {
  const routeSegments = pathname.split('/').filter(Boolean);
  if (routeSegments.length !== 2) {
    return null;
  }
  const [languageSegment, authSegment] = routeSegments;
  const candidateLanguage = languageSegment ?? '';
  if (!isCourseRouteLanguage(candidateLanguage) || typeof authSegment !== 'string') {
    return null;
  }
  const language = candidateLanguage;
  const mode = (['signIn', 'signUp'] as const).find(
    (candidateMode) => authSlugByLanguage[language][candidateMode] === authSegment,
  );
  return mode === undefined ? null : { language, mode };
};

/*
 * Accepts either language's slug so that a mismatched pairing such as
 * `/en/ochrana-osobnich-udaju` is still recognised as the privacy notice and
 * still offers a working switch back to its canonical counterpart.
 */
export const parseLegalRoutePath = (pathname: string): LegalRouteMatch | null => {
  const routeSegments = pathname.split('/').filter(Boolean);
  if (routeSegments.length !== 2) {
    return null;
  }
  const [languageSegment, legalSegment] = routeSegments;
  const candidateLanguage = languageSegment ?? '';
  if (!isCourseRouteLanguage(candidateLanguage) || typeof legalSegment !== 'string') {
    return null;
  }
  const document = legalDocuments.find((candidate) =>
    (['cs', 'en'] as const).some(
      (slugLanguage) => legalSlugByLanguage[slugLanguage][candidate] === legalSegment,
    ),
  );
  return document === undefined ? null : { document, language: candidateLanguage };
};

export const localizedPathForLanguage = (pathname: string, language: CourseRouteLanguage) => {
  const courseRoute = parseCourseRoutePath(pathname);
  if (courseRoute !== null) {
    return courseRoutePath(language, courseRoute.draftId, courseRoute.step);
  }
  const authRoute = parseAuthRoutePath(pathname);
  if (authRoute !== null) {
    return authRoutePath(language, authRoute.mode);
  }
  const legalRoute = parseLegalRoutePath(pathname);
  if (legalRoute !== null) {
    return legalRoutePath(language, legalRoute.document);
  }
  const [languageSegment, dashboardSegment] = pathname.split('/').filter(Boolean);
  const candidateDashboardLanguage = languageSegment ?? '';
  if (
    isCourseRouteLanguage(candidateDashboardLanguage) &&
    dashboardSegment === dashboardSlugByLanguage[candidateDashboardLanguage]
  ) {
    return dashboardRoutePath(language);
  }
  const segments = pathname.split('/').filter(Boolean);
  if (isCourseRouteLanguage(segments[0] ?? '')) {
    segments.shift();
  }
  return segments.length === 0 ? `/${language}` : `/${language}/${segments.join('/')}`;
};
